FROM amazonlinux:2.0.20191217.0

# setup build env
RUN yum -y install curl rpm-build tar make readline-devel ncurses-devel gdbm-devel glibc-devel gcc openssl-devel libyaml-devel libffi-devel zlib-devel

# rpmbuild command recommends to use `builder:builder` as user:group.
RUN useradd -u 1000 builder

RUN mkdir -p /home/builder/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
RUN chown -R builder:builder /home/builder/rpmbuild

WORKDIR /home/builder/rpmbuild
